name: Examples

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tutorials:
    name: Examples
    runs-on: ubuntu-latest

    env:
      DEVITO_ARCH: gcc
      DEVITO_LANGUAGE: "openmp"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false
      matrix:
        ndim: ['1', '2', '3']

    steps:
    - name: Checkout devito
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .

    - name: Seismic acoustic examples
      run: |
        python seismic/acoustic/acoustic_example.py --full -nd ${{ matrix.ndim }}
        python seismic/acoustic/acoustic_example.py --constant --full -nd ${{ matrix.ndim }}

    - name: Seismic advanced examples
      if:  matrix.ndim > 1
      run: |
        python seismic/acoustic/acoustic_example.py --full --checkpointing -nd ${{ matrix.ndim }}
        python seismic/tti/tti_example.py -a basic -nd ${{ matrix.ndim }}
        python seismic/tti/tti_example.py -a basic --noazimuth -nd ${{ matrix.ndim }}
        python seismic/elastic/elastic_example.py -nd ${{ matrix.ndim }}
        python seismic/viscoelastic/viscoelastic_example.py -nd ${{ matrix.ndim }}

    - name: Tutorials
      if:  matrix.ndim > 1
      run: py.test --nbval --ignore-glob=seismic/tutorials/TLE*.ipynb seismic/tutorials/
